# Generated by Django 5.1.3 on 2024-11-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_customuser_username_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('diurno_nocturno', models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno')], default='Diurno', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='usuarios.asignatura'),
        ),
    ]
