# Generated by Django 5.1.3 on 2024-12-01 08:15

import django.core.validators
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_customuser_avatar_customuser_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), usuarios.models.validate_avatar_size]),
        ),
    ]
