# Generated by Django 5.1.3 on 2024-12-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfilpanolero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilpanolero',
            name='usuario',
        ),
    ]
