# Generated by Django 5.1.3 on 2024-12-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_perfilpanolero_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilPanolero',
        ),
    ]
