# Generated by Django 5.1.3 on 2024-11-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Devuelta', 'Devuelta'), ('Rota', 'Rota')], max_length=50),
        ),
    ]
