# Generated by Django 5.1.3 on 2024-11-29 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_herramienta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha_devolucion',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='nombre_usuario',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='rut_usuario',
        ),
        migrations.AddField(
            model_name='herramienta',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='SolicitudesHerramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.herramienta')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_herramientas', to='solicitudes.solicitud')),
            ],
        ),
    ]
