# Generated by Django 5.1.3 on 2024-11-30 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_remove_solicitud_cantidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaherramienta',
            options={'verbose_name_plural': 'Categorías de Herramientas'},
        ),
        migrations.AlterModelOptions(
            name='herramienta',
            options={'verbose_name_plural': 'Herramientas'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.RemoveField(
            model_name='herramienta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='herramienta',
            name='estado',
        ),
        migrations.AddField(
            model_name='categoriaherramienta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='herramientas/'),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='stock_disponible',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='stock_total',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoriaherramienta',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='solicitudes.categoriaherramienta'),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.herramienta')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Solicitudes',
                'unique_together': {('solicitud', 'herramienta')},
            },
        ),
        migrations.DeleteModel(
            name='SolicitudesHerramientas',
        ),
    ]
