# Generated by Django 5.1.3 on 2024-12-01 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_rename_fecha_solicitud_solicitud_created_at_and_more'),
        ('usuarios', '0004_asignatura_customuser_asignaturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha_devolucion_real',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha_retiro_real',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.asignatura'),
        ),
    ]
