# Generated by Django 5.1.3 on 2024-12-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_remove_solicitud_fecha_devolucion_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
