# Generated by Django 5.1.3 on 2024-12-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_reporteherramienta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReporteHerramienta',
        ),
    ]
