# Generated by Django 5.1.3 on 2024-12-02 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_herramienta_rota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='reportado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='rota',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Herramienta_rota',
        ),
    ]
