# Generated by Django 5.1.3 on 2024-12-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0015_reporteherramienta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='fecha_reporte_rota',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
