# Generated by Django 5.1.3 on 2024-12-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0019_alumno_solicitud_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
    ]
