# Generated by Django 5.1.3 on 2024-12-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0020_activofijo_prioridad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activofijo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='activofijo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='solicitudes.categoriaherramienta'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='fecha_reporte_roto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='reportado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='roto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='stock_disponible',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='stock_total',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
