# Generated by Django 5.1.3 on 2024-12-10 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0021_remove_activofijo_tipo_activofijo_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleActivoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.activofijo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_activos', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de Activo en Solicitud',
                'verbose_name_plural': 'Detalles de Activos en Solicitudes',
                'unique_together': {('solicitud', 'activo')},
            },
        ),
    ]
