# Generated by Django 5.1.3 on 2024-12-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0025_remove_registrousosala_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='profesor',
        ),
    ]
